-- Every arena players can vote for. Each entry controls the island's size, terrain shape and features
-- (rivers, mesas, a volcano), materials, decoration, landmarks, the look of the cornucopia, lighting,
-- clouds and weather. Add a new table to add a map.

local MapDefs = {}

local M = Enum.Material

export type Style = {
	stone: Enum.Material,
	stoneColors: { Color3 },
	floor: Enum.Material,
	floorColor: Color3,
	shrine: Enum.Material,
	shrineColor: Color3,
	wood: Color3,
	accent: Color3,
	plaza: Enum.Material,
	plazaColor: Color3,
	plazaColor2: Color3, -- the inlaid rings and spokes of the cornucopia floor
	dais: Enum.Material,
	daisColor: Color3,
	banner: { Color3 }, -- banner / awning / tent cloth colours
	flair: string, -- the cornucopia's themed decoration (see Structures.cornucopia)
}

export type Decor = {
	kind: string, -- "tree" | "rock" | "bush"
	styles: { string },
	count: number,
	cluster: { number }?, -- {min, max}: place in little groups instead of one by one
	spread: number?, -- how far a cluster spreads (studs)
	nearWater: number?, -- only within this many studs of water / lava / ice
}

export type MapDef = {
	id: string,
	name: string,
	icon: string,
	description: string,
	radius: number,
	terrain: {
		base: number,
		hills: number,
		hillScale: number,
		detail: number,
		rough: number,
		mountains: number,
		liquidLevel: number,
		liquid: Enum.Material,
		peakHeight: number,
		cliffHeight: number,
		-- optional features
		river: { scale: number, width: number, depth: number, dry: boolean? }?,
		mesas: { scale: number, threshold: number, step: number, steps: number }?,
		volcano: { height: number, radius: number, crater: number }?,
	},
	materials: {
		surface: Enum.Material,
		alt: Enum.Material,
		alt2: Enum.Material,
		shore: Enum.Material,
		cliff: Enum.Material,
		peak: Enum.Material,
		under: Enum.Material,
		path: Enum.Material,
		riverbed: Enum.Material?, -- dry rivers
		wet: { material: Enum.Material, height: number }?, -- a band of this just above the waterline
		patches: { { material: Enum.Material, scale: number, threshold: number } }?,
		strata: { Enum.Material }?, -- striped cliffs, bottom to top
	},
	colors: { [Enum.Material]: Color3 },
	paths: { width: number, crossing: string }, -- crossing: "bridge" | "causeway" | "none"
	decor: { Decor },
	pois: { string },
	poiCount: number,
	outerChests: number,
	style: Style,
	lighting: { [string]: any },
	atmosphere: { [string]: any },
	post: {
		saturation: number,
		contrast: number,
		brightness: number,
		tint: Color3,
		bloom: number,
		sunRays: number,
	},
	clouds: { cover: number, density: number, color: Color3 }?,
	water: { color: Color3, transparency: number, reflectance: number?, waves: number? },
	sky: string?, -- extra sky dressing: "Aurora"
	weather: string?,
	hazard: string?,
}

-- Terrain colours shared by every map; each map overrides what it needs.
local BASE_COLORS = {
	[M.Grass] = Color3.fromRGB(106, 140, 66),
	[M.LeafyGrass] = Color3.fromRGB(96, 128, 62),
	[M.Ground] = Color3.fromRGB(110, 92, 64),
	[M.Sand] = Color3.fromRGB(196, 178, 128),
	[M.Rock] = Color3.fromRGB(110, 110, 112),
	[M.Snow] = Color3.fromRGB(232, 238, 248),
	[M.Glacier] = Color3.fromRGB(150, 205, 240),
	[M.Slate] = Color3.fromRGB(88, 92, 98),
	[M.Basalt] = Color3.fromRGB(42, 40, 44),
	[M.CrackedLava] = Color3.fromRGB(255, 110, 30),
	[M.Sandstone] = Color3.fromRGB(196, 150, 104),
	[M.Mud] = Color3.fromRGB(70, 56, 44),
	[M.Cobblestone] = Color3.fromRGB(128, 122, 112),
	[M.Limestone] = Color3.fromRGB(220, 200, 170),
	[M.Ice] = Color3.fromRGB(170, 220, 245),
	[M.Salt] = Color3.fromRGB(225, 220, 210),
	[M.Pavement] = Color3.fromRGB(140, 136, 128),
}

local function colors(overrides: { [Enum.Material]: Color3 }?): { [Enum.Material]: Color3 }
	local out = table.clone(BASE_COLORS)
	for k, v in (overrides or {}) :: { [Enum.Material]: Color3 } do
		out[k] = v
	end
	return out
end

local rgb = Color3.fromRGB

MapDefs.List = {
	---------------------------------------------------------------------------
	-- Verdant Isle: a bright spring island of meadows, flowers, a winding river and an ancient oak
	---------------------------------------------------------------------------
	{
		id = "Verdant",
		name = "Verdant Isle",
		icon = "🌳",
		description = "Flower meadows, a winding river, a windmill and the Ancient Oak. The classic.",
		radius = 450,
		terrain = {
			base = 12,
			hills = 34,
			hillScale = 170,
			detail = 12,
			rough = 2.5,
			mountains = 95,
			liquidLevel = 4,
			liquid = M.Water,
			peakHeight = 92,
			cliffHeight = 58,
			river = { scale = 300, width = 0.03, depth = 7 },
		},
		materials = {
			surface = M.Grass,
			alt = M.LeafyGrass,
			alt2 = M.Ground,
			shore = M.Sand,
			cliff = M.Rock,
			peak = M.Snow,
			under = M.Ground,
			path = M.Ground,
			wet = { material = M.LeafyGrass, height = 2.5 },
			patches = {
				{ material = M.LeafyGrass, scale = 70, threshold = 0.22 },
				{ material = M.Mud, scale = 30, threshold = 0.42 },
				{ material = M.Cobblestone, scale = 24, threshold = 0.47 },
			},
		},
		colors = colors({
			[M.Grass] = rgb(104, 158, 62),
			[M.LeafyGrass] = rgb(78, 136, 56),
			[M.Ground] = rgb(128, 98, 66),
			[M.Sand] = rgb(222, 204, 150),
			[M.Rock] = rgb(118, 116, 122),
			[M.Mud] = rgb(92, 72, 52),
			[M.Cobblestone] = rgb(130, 128, 120),
		}),
		paths = { width = 5, crossing = "bridge" },
		decor = {
			{ kind = "tree", styles = { "oak", "oak", "oak", "birch", "pine", "autumn" }, count = 280 },
			{ kind = "rock", styles = { "mossystone", "stone" }, count = 90 },
			{ kind = "bush", styles = { "bush", "berrybush" }, count = 140 },
			{ kind = "bush", styles = { "flower" }, count = 90, cluster = { 5, 10 }, spread = 6 },
			{ kind = "bush", styles = { "tallgrass" }, count = 160, cluster = { 2, 4 }, spread = 4 },
			{ kind = "bush", styles = { "log", "mushroomring" }, count = 30 },
			{ kind = "bush", styles = { "reeds" }, count = 50, cluster = { 3, 6 }, spread = 4, nearWater = 10 },
		},
		pois = { "ruinedTower", "ancientOak", "camp", "shrine", "windmill", "watchtower" },
		poiCount = 10,
		outerChests = 30,
		style = {
			stone = M.Cobblestone,
			stoneColors = { rgb(140, 138, 140), rgb(120, 118, 114), rgb(156, 152, 142) },
			floor = M.Cobblestone,
			floorColor = rgb(124, 120, 116),
			shrine = M.Marble,
			shrineColor = rgb(238, 234, 226),
			wood = rgb(120, 84, 52),
			accent = rgb(140, 110, 255),
			plaza = M.Cobblestone,
			plazaColor = rgb(150, 146, 138),
			plazaColor2 = rgb(104, 132, 84),
			dais = M.Marble,
			daisColor = rgb(232, 226, 214),
			banner = { rgb(200, 50, 60), rgb(40, 110, 200), rgb(240, 190, 50), rgb(60, 150, 70) },
			flair = "flowers",
		},
		lighting = {
			ClockTime = 14.2,
			Brightness = 2.8,
			OutdoorAmbient = rgb(136, 136, 146),
			Ambient = rgb(70, 70, 82),
			ColorShift_Top = rgb(255, 240, 215),
			EnvironmentDiffuseScale = 1,
			EnvironmentSpecularScale = 1,
		},
		atmosphere = {
			Density = 0.24,
			Offset = 0.12,
			Color = rgb(196, 214, 240),
			Decay = rgb(120, 130, 170),
			Glare = 0.3,
			Haze = 1.2,
		},
		post = {
			saturation = 0.22,
			contrast = 0.08,
			brightness = 0.02,
			tint = rgb(255, 250, 240),
			bloom = 0.6,
			sunRays = 0.08,
		},
		clouds = { cover = 0.55, density = 0.6, color = rgb(255, 255, 255) },
		water = { color = rgb(46, 140, 170), transparency = 0.55, reflectance = 0.6, waves = 0.12 },
		weather = "Pollen",
	},
	---------------------------------------------------------------------------
	-- Frostpeak: glittering snowfields, a frozen river, glowing ice spires and an aurora at dusk
	---------------------------------------------------------------------------
	{
		id = "Frostpeak",
		name = "Frostpeak",
		icon = "🏔️",
		description = "Snowfields under an aurora: frozen rivers, glowing ice spires and a cosy hunter's lodge.",
		radius = 420,
		terrain = {
			base = 14,
			hills = 44,
			hillScale = 150,
			detail = 15,
			rough = 4,
			mountains = 120,
			liquidLevel = 5,
			liquid = M.Glacier,
			peakHeight = 70,
			cliffHeight = 50,
			river = { scale = 260, width = 0.032, depth = 6 },
		},
		materials = {
			surface = M.Snow,
			alt = M.Snow,
			alt2 = M.Ice,
			shore = M.Glacier,
			cliff = M.Slate,
			peak = M.Snow,
			under = M.Rock,
			path = M.Slate,
			patches = {
				{ material = M.Slate, scale = 34, threshold = 0.4 },
				{ material = M.Ice, scale = 50, threshold = 0.38 },
				{ material = M.Rock, scale = 20, threshold = 0.46 },
			},
		},
		colors = colors({
			[M.Snow] = rgb(236, 242, 255),
			[M.Ice] = rgb(160, 214, 250),
			[M.Glacier] = rgb(110, 196, 245),
			[M.Slate] = rgb(92, 104, 128),
			[M.Rock] = rgb(108, 116, 134),
		}),
		paths = { width = 4.5, crossing = "none" },
		decor = {
			{ kind = "tree", styles = { "snowpine", "snowpine", "snowpine", "frostbirch" }, count = 260 },
			{ kind = "rock", styles = { "ice", "crystal", "snowstone" }, count = 110 },
			{ kind = "bush", styles = { "snowdrift", "frostbush" }, count = 140 },
			{ kind = "bush", styles = { "snowman" }, count = 4 },
			{ kind = "bush", styles = { "icicles" }, count = 40, cluster = { 2, 4 }, spread = 5 },
		},
		pois = { "ruinedTower", "iceSpire", "watchtower", "shrine", "lodge", "camp" },
		poiCount = 9,
		outerChests = 28,
		style = {
			stone = M.Slate,
			stoneColors = { rgb(124, 136, 160), rgb(104, 116, 138), rgb(146, 158, 176) },
			floor = M.Slate,
			floorColor = rgb(112, 124, 146),
			shrine = M.Marble,
			shrineColor = rgb(218, 232, 248),
			wood = rgb(100, 72, 52),
			accent = rgb(100, 230, 255),
			plaza = M.Slate,
			plazaColor = rgb(150, 168, 196),
			plazaColor2 = rgb(96, 170, 220),
			dais = M.Marble,
			daisColor = rgb(226, 238, 250),
			banner = { rgb(60, 120, 220), rgb(240, 245, 255), rgb(150, 80, 220), rgb(60, 190, 210) },
			flair = "crystals",
		},
		lighting = {
			ClockTime = 17.4,
			Brightness = 2.2,
			OutdoorAmbient = rgb(150, 150, 190),
			Ambient = rgb(80, 80, 110),
			ColorShift_Top = rgb(255, 200, 220),
			EnvironmentDiffuseScale = 1,
			EnvironmentSpecularScale = 1,
		},
		atmosphere = {
			Density = 0.34,
			Offset = 0.1,
			Color = rgb(226, 214, 246),
			Decay = rgb(150, 140, 220),
			Glare = 0.35,
			Haze = 1.8,
		},
		post = {
			saturation = 0.18,
			contrast = 0.1,
			brightness = 0.02,
			tint = rgb(245, 240, 255),
			bloom = 0.8,
			sunRays = 0.12,
		},
		clouds = { cover = 0.6, density = 0.45, color = rgb(255, 225, 240) },
		water = { color = rgb(80, 150, 200), transparency = 0.5 },
		sky = "Aurora",
		weather = "Snow",
	},
	---------------------------------------------------------------------------
	-- Ashen Wastes: a smoking volcano, rivers of lava, obsidian and basalt columns
	---------------------------------------------------------------------------
	{
		id = "Ashen",
		name = "Ashen Wastes",
		icon = "🌋",
		description = "Rivers of lava under a smoking volcano. Black glass, ember vents and a dwarven forge.",
		radius = 400,
		terrain = {
			base = 14,
			hills = 30,
			hillScale = 140,
			detail = 16,
			rough = 5,
			mountains = 100,
			liquidLevel = 6,
			liquid = M.CrackedLava,
			peakHeight = 999,
			cliffHeight = 46,
			river = { scale = 240, width = 0.022, depth = 5 },
			volcano = { height = 150, radius = 170, crater = 30 },
		},
		materials = {
			surface = M.Basalt,
			alt = M.Slate,
			alt2 = M.Ground,
			shore = M.Basalt,
			cliff = M.Rock,
			peak = M.Basalt,
			under = M.Basalt,
			path = M.Asphalt,
			patches = {
				{ material = M.Ground, scale = 60, threshold = 0.2 },
				{ material = M.Salt, scale = 22, threshold = 0.5 },
				{ material = M.Slate, scale = 36, threshold = 0.3 },
			},
			strata = { M.Basalt, M.Basalt, M.Rock, M.Basalt, M.Slate, M.Basalt },
		},
		colors = colors({
			[M.Basalt] = rgb(38, 34, 38),
			[M.Ground] = rgb(84, 70, 66),
			[M.Slate] = rgb(62, 56, 60),
			[M.Rock] = rgb(86, 70, 66),
			[M.Salt] = rgb(214, 196, 80),
			[M.Asphalt] = rgb(58, 52, 54),
			[M.CrackedLava] = rgb(255, 104, 24),
		}),
		paths = { width = 5, crossing = "causeway" },
		decor = {
			{ kind = "tree", styles = { "dead", "dead", "charred" }, count = 130 },
			{ kind = "rock", styles = { "obsidian", "basalt", "basalt", "stone", "redcrystal" }, count = 120 },
			{ kind = "bush", styles = { "ashpile", "ashpile", "embers" }, count = 80 },
			{ kind = "bush", styles = { "vent" }, count = 14 },
			{ kind = "bush", styles = { "bones" }, count = 10 },
		},
		pois = { "ruinedTower", "forge", "watchtower", "obsidianGate", "shrine", "camp" },
		poiCount = 9,
		outerChests = 26,
		style = {
			stone = M.Basalt,
			stoneColors = { rgb(60, 54, 56), rgb(76, 66, 62), rgb(48, 44, 48) },
			floor = M.Basalt,
			floorColor = rgb(54, 48, 50),
			shrine = M.Basalt,
			shrineColor = rgb(66, 56, 58),
			wood = rgb(60, 42, 32),
			accent = rgb(255, 120, 40),
			plaza = M.Basalt,
			plazaColor = rgb(64, 56, 58),
			plazaColor2 = rgb(150, 50, 30),
			dais = M.Slate,
			daisColor = rgb(90, 76, 74),
			banner = { rgb(170, 30, 30), rgb(40, 34, 38), rgb(230, 120, 30), rgb(110, 20, 20) },
			flair = "braziers",
		},
		lighting = {
			ClockTime = 18.2,
			Brightness = 1.9,
			OutdoorAmbient = rgb(156, 100, 84),
			Ambient = rgb(90, 50, 44),
			ColorShift_Top = rgb(255, 150, 90),
			EnvironmentDiffuseScale = 1,
			EnvironmentSpecularScale = 1,
		},
		atmosphere = {
			Density = 0.42,
			Offset = 0.2,
			Color = rgb(206, 130, 100),
			Decay = rgb(126, 46, 36),
			Glare = 0.5,
			Haze = 2.4,
		},
		post = {
			saturation = 0.16,
			contrast = 0.14,
			brightness = 0,
			tint = rgb(255, 232, 216),
			bloom = 1.1,
			sunRays = 0.1,
		},
		clouds = { cover = 0.75, density = 0.7, color = rgb(120, 90, 90) },
		water = { color = rgb(60, 60, 60), transparency = 0.6 },
		weather = "Ash",
		hazard = "Lava",
	},
	---------------------------------------------------------------------------
	-- Sandsea Ruins: striped canyon mesas, palm oases, a step pyramid and a colourful bazaar
	---------------------------------------------------------------------------
	{
		id = "Sandsea",
		name = "Sandsea Ruins",
		icon = "🏜️",
		description = "Striped canyon mesas, palm oases, a step pyramid and a bazaar. The biggest map.",
		radius = 480,
		terrain = {
			base = 12,
			hills = 26,
			hillScale = 120,
			detail = 9,
			rough = 1.5,
			mountains = 75,
			liquidLevel = 2,
			liquid = M.Water,
			peakHeight = 999,
			cliffHeight = 70,
			river = { scale = 320, width = 0.03, depth = 3, dry = true },
			mesas = { scale = 120, threshold = 0.3, step = 5.5, steps = 3 },
		},
		materials = {
			surface = M.Sand,
			alt = M.Sand,
			alt2 = M.Sandstone,
			shore = M.LeafyGrass,
			cliff = M.Sandstone,
			peak = M.Sandstone,
			under = M.Sandstone,
			path = M.Pavement,
			riverbed = M.Ground,
			wet = { material = M.Grass, height = 4 },
			patches = {
				{ material = M.Sandstone, scale = 55, threshold = 0.35 },
				{ material = M.Ground, scale = 28, threshold = 0.47 },
			},
			strata = { M.Sandstone, M.Limestone, M.Sandstone, M.Rock, M.Sandstone, M.Salt },
		},
		colors = colors({
			[M.Sand] = rgb(232, 196, 130),
			[M.Sandstone] = rgb(204, 120, 76),
			[M.Limestone] = rgb(238, 206, 160),
			[M.Rock] = rgb(170, 84, 60),
			[M.Salt] = rgb(246, 226, 190),
			[M.Ground] = rgb(170, 128, 86),
			[M.Grass] = rgb(110, 160, 60),
			[M.LeafyGrass] = rgb(84, 146, 60),
			[M.Pavement] = rgb(214, 184, 140),
		}),
		paths = { width = 5, crossing = "bridge" },
		decor = {
			{ kind = "tree", styles = { "cactus", "cactus", "cactus" }, count = 140 },
			{ kind = "tree", styles = { "palm" }, count = 60, nearWater = 24 },
			{ kind = "rock", styles = { "sandstone", "hoodoo", "hoodoo" }, count = 110 },
			{ kind = "bush", styles = { "shrub", "shrub", "urn", "bones" }, count = 90 },
			{ kind = "bush", styles = { "desertflower" }, count = 50, cluster = { 3, 6 }, spread = 5 },
			{ kind = "bush", styles = { "reeds" }, count = 40, cluster = { 3, 6 }, spread = 4, nearWater = 10 },
		},
		pois = { "ruinedTower", "pyramid", "camp", "bazaar", "shrine", "watchtower" },
		poiCount = 11,
		outerChests = 30,
		style = {
			stone = M.Sandstone,
			stoneColors = { rgb(216, 176, 122), rgb(198, 156, 106), rgb(226, 192, 144) },
			floor = M.Sandstone,
			floorColor = rgb(208, 170, 118),
			shrine = M.Sandstone,
			shrineColor = rgb(232, 202, 154),
			wood = rgb(126, 92, 56),
			accent = rgb(255, 196, 60),
			plaza = M.Sandstone,
			plazaColor = rgb(222, 188, 136),
			plazaColor2 = rgb(40, 130, 160),
			dais = M.Marble,
			daisColor = rgb(240, 226, 196),
			banner = { rgb(200, 40, 60), rgb(30, 120, 170), rgb(240, 170, 30), rgb(120, 50, 150) },
			flair = "obelisks",
		},
		lighting = {
			ClockTime = 15.6,
			Brightness = 3.1,
			OutdoorAmbient = rgb(170, 146, 122),
			Ambient = rgb(90, 74, 60),
			ColorShift_Top = rgb(255, 225, 180),
			EnvironmentDiffuseScale = 1,
			EnvironmentSpecularScale = 1,
		},
		atmosphere = {
			Density = 0.28,
			Offset = 0.08,
			Color = rgb(246, 220, 176),
			Decay = rgb(214, 150, 96),
			Glare = 0.7,
			Haze = 1.8,
		},
		post = {
			saturation = 0.24,
			contrast = 0.1,
			brightness = 0.01,
			tint = rgb(255, 244, 228),
			bloom = 0.55,
			sunRays = 0.1,
		},
		clouds = { cover = 0.4, density = 0.35, color = rgb(255, 246, 230) },
		water = { color = rgb(30, 170, 170), transparency = 0.45, reflectance = 0.7, waves = 0.08 },
		weather = "Dust",
	},
	---------------------------------------------------------------------------
	-- Fungal Hollow: a glowing night forest of giant mushrooms, fairy rings and fireflies
	---------------------------------------------------------------------------
	{
		id = "Fungal",
		name = "Fungal Hollow",
		icon = "🍄",
		description = "A glowing night forest of giant mushrooms, fairy rings and fireflies. Small and deadly.",
		radius = 380,
		terrain = {
			base = 12,
			hills = 30,
			hillScale = 140,
			detail = 12,
			rough = 3,
			mountains = 95,
			liquidLevel = 5,
			liquid = M.Water,
			peakHeight = 999,
			cliffHeight = 54,
			river = { scale = 230, width = 0.03, depth = 6 },
		},
		materials = {
			surface = M.LeafyGrass,
			alt = M.Grass,
			alt2 = M.Mud,
			shore = M.Mud,
			cliff = M.Rock,
			peak = M.Rock,
			under = M.Mud,
			path = M.Cobblestone,
			patches = {
				{ material = M.Grass, scale = 60, threshold = 0.2 },
				{ material = M.Ground, scale = 34, threshold = 0.38 },
				{ material = M.Mud, scale = 24, threshold = 0.46 },
			},
		},
		colors = colors({
			[M.LeafyGrass] = rgb(56, 112, 112),
			[M.Grass] = rgb(96, 76, 140),
			[M.Mud] = rgb(52, 40, 60),
			[M.Rock] = rgb(74, 66, 92),
			[M.Ground] = rgb(54, 90, 80),
			[M.Cobblestone] = rgb(90, 86, 116),
		}),
		paths = { width = 4.5, crossing = "bridge" },
		decor = {
			{
				kind = "tree",
				styles = { "bigmushroom", "bigmushroom", "conemushroom", "mushroomcluster" },
				count = 130,
			},
			{ kind = "rock", styles = { "mossy", "shelf", "crystal" }, count = 80 },
			{ kind = "bush", styles = { "smallmushroom" }, count = 150, cluster = { 2, 5 }, spread = 4 },
			{ kind = "bush", styles = { "glowflower" }, count = 70, cluster = { 3, 6 }, spread = 5 },
			{ kind = "bush", styles = { "fireflies" }, count = 24 },
			{ kind = "bush", styles = { "reeds" }, count = 40, cluster = { 3, 6 }, spread = 4, nearWater = 10 },
		},
		pois = { "ruinedTower", "fairyRing", "camp", "stump", "shrine", "watchtower" },
		poiCount = 8,
		outerChests = 24,
		style = {
			stone = M.Slate,
			stoneColors = { rgb(84, 100, 96), rgb(72, 84, 90), rgb(100, 110, 104) },
			floor = M.Slate,
			floorColor = rgb(78, 88, 90),
			shrine = M.Marble,
			shrineColor = rgb(196, 180, 228),
			wood = rgb(84, 62, 74),
			accent = rgb(90, 255, 220),
			plaza = M.Slate,
			plazaColor = rgb(84, 86, 112),
			plazaColor2 = rgb(60, 150, 140),
			dais = M.Marble,
			daisColor = rgb(186, 174, 220),
			banner = { rgb(130, 60, 200), rgb(40, 170, 160), rgb(220, 80, 160), rgb(60, 90, 200) },
			flair = "mushrooms",
		},
		lighting = {
			ClockTime = 0.4,
			Brightness = 1.4,
			OutdoorAmbient = rgb(118, 100, 162),
			Ambient = rgb(70, 56, 110),
			ColorShift_Top = rgb(170, 140, 255),
			EnvironmentDiffuseScale = 1,
			EnvironmentSpecularScale = 1,
		},
		atmosphere = {
			Density = 0.38,
			Offset = 0.22,
			Color = rgb(150, 120, 210),
			Decay = rgb(60, 36, 120),
			Glare = 0,
			Haze = 2.2,
		},
		post = {
			saturation = 0.3,
			contrast = 0.12,
			brightness = 0.03,
			tint = rgb(240, 236, 255),
			bloom = 1.2,
			sunRays = 0,
		},
		clouds = { cover = 0.35, density = 0.3, color = rgb(120, 100, 170) },
		water = { color = rgb(60, 110, 160), transparency = 0.45, reflectance = 0.5, waves = 0.06 },
		weather = "Spores",
	},
} :: { MapDef }

MapDefs.ById = {} :: { [string]: MapDef }
for _, def in MapDefs.List do
	MapDefs.ById[def.id] = def
end

-- The plaza (and pedestal ring) are flattened to this height.
function MapDefs.plazaHeight(def: MapDef): number
	return def.terrain.base + 1
end

-- What the vote screen needs to know (plain data so it can go over a remote).
function MapDefs.summary(def: MapDef): { [string]: any }
	return {
		id = def.id,
		name = def.name,
		icon = def.icon,
		description = def.description,
		radius = def.radius,
	}
end

return MapDefs
