-- Every arena players can vote for. Each entry controls the island's size, terrain shape,
-- materials, decoration, ruin style, lighting and weather. Add a new table to add a map.

local MapDefs = {}

local M = Enum.Material

export type Style = {
	stone: Enum.Material,
	stoneColors: { Color3 },
	floor: Enum.Material,
	floorColor: Color3,
	shrine: Enum.Material,
	shrineColor: Color3,
	wood: Color3,
	accent: Color3,
	plaza: Enum.Material,
	plazaColor: Color3,
	dais: Enum.Material,
	daisColor: Color3,
}

export type MapDef = {
	id: string,
	name: string,
	icon: string,
	description: string,
	radius: number,
	terrain: {
		base: number,
		hills: number,
		hillScale: number,
		detail: number,
		rough: number,
		mountains: number,
		liquidLevel: number,
		liquid: Enum.Material,
		peakHeight: number,
		cliffHeight: number,
	},
	materials: {
		surface: Enum.Material,
		alt: Enum.Material,
		alt2: Enum.Material,
		shore: Enum.Material,
		cliff: Enum.Material,
		peak: Enum.Material,
		under: Enum.Material,
	},
	colors: { [Enum.Material]: Color3 },
	decor: { { kind: string, styles: { string }, count: number } },
	pois: { string },
	poiCount: number,
	outerChests: number,
	style: Style,
	lighting: { [string]: any },
	atmosphere: { [string]: any },
	water: { color: Color3, transparency: number },
	weather: string?,
	hazard: string?,
}

-- Terrain colours shared by every map; each map overrides what it needs.
local BASE_COLORS = {
	[M.Grass] = Color3.fromRGB(106, 140, 66),
	[M.LeafyGrass] = Color3.fromRGB(96, 128, 62),
	[M.Ground] = Color3.fromRGB(110, 92, 64),
	[M.Sand] = Color3.fromRGB(196, 178, 128),
	[M.Rock] = Color3.fromRGB(110, 110, 112),
	[M.Snow] = Color3.fromRGB(232, 238, 248),
	[M.Glacier] = Color3.fromRGB(150, 205, 240),
	[M.Slate] = Color3.fromRGB(88, 92, 98),
	[M.Basalt] = Color3.fromRGB(42, 40, 44),
	[M.CrackedLava] = Color3.fromRGB(255, 110, 30),
	[M.Sandstone] = Color3.fromRGB(196, 150, 104),
	[M.Mud] = Color3.fromRGB(70, 56, 44),
}

local function colors(overrides: { [Enum.Material]: Color3 }?): { [Enum.Material]: Color3 }
	local out = table.clone(BASE_COLORS)
	for k, v in (overrides or {}) :: { [Enum.Material]: Color3 } do
		out[k] = v
	end
	return out
end

local ALL_POIS = { "ruinedTower", "shrine", "camp", "watchtower" }

MapDefs.List = {
	{
		id = "Verdant",
		name = "Verdant Isle",
		icon = "🌳",
		description = "Rolling green hills, quiet lakes and crumbling ruins. The classic.",
		radius = 450,
		terrain = {
			base = 12,
			hills = 36,
			hillScale = 170,
			detail = 13,
			rough = 3,
			mountains = 85,
			liquidLevel = 4,
			liquid = M.Water,
			peakHeight = 80,
			cliffHeight = 52,
		},
		materials = {
			surface = M.Grass,
			alt = M.LeafyGrass,
			alt2 = M.Ground,
			shore = M.Sand,
			cliff = M.Rock,
			peak = M.Snow,
			under = M.Ground,
		},
		colors = colors(),
		decor = {
			{ kind = "tree", styles = { "oak", "oak", "pine", "birch" }, count = 300 },
			{ kind = "rock", styles = { "stone" }, count = 120 },
			{ kind = "bush", styles = { "bush" }, count = 180 },
		},
		pois = ALL_POIS,
		poiCount = 10,
		outerChests = 30,
		style = {
			stone = M.Cobblestone,
			stoneColors = {
				Color3.fromRGB(130, 130, 135),
				Color3.fromRGB(115, 112, 110),
				Color3.fromRGB(150, 148, 140),
			},
			floor = M.Cobblestone,
			floorColor = Color3.fromRGB(120, 118, 115),
			shrine = M.Marble,
			shrineColor = Color3.fromRGB(235, 232, 225),
			wood = Color3.fromRGB(110, 80, 50),
			accent = Color3.fromRGB(150, 100, 255),
			plaza = M.Slate,
			plazaColor = Color3.fromRGB(105, 105, 115),
			dais = M.Marble,
			daisColor = Color3.fromRGB(225, 220, 210),
		},
		lighting = { ClockTime = 14.5, Brightness = 2.5, OutdoorAmbient = Color3.fromRGB(128, 128, 140) },
		atmosphere = {
			Density = 0.28,
			Offset = 0.15,
			Color = Color3.fromRGB(200, 205, 230),
			Decay = Color3.fromRGB(110, 100, 140),
			Glare = 0.25,
			Haze = 1.4,
		},
		water = { color = Color3.fromRGB(60, 130, 170), transparency = 0.6 },
	},
	{
		id = "Frostpeak",
		name = "Frostpeak",
		icon = "🏔️",
		description = "A snowbound island of frozen lakes, pine forests and towering peaks.",
		radius = 420,
		terrain = {
			base = 14,
			hills = 44,
			hillScale = 150,
			detail = 15,
			rough = 4,
			mountains = 110,
			liquidLevel = 5,
			liquid = M.Glacier,
			peakHeight = 60,
			cliffHeight = 48,
		},
		materials = {
			surface = M.Snow,
			alt = M.Snow,
			alt2 = M.Glacier,
			shore = M.Glacier,
			cliff = M.Slate,
			peak = M.Snow,
			under = M.Rock,
		},
		colors = colors({ [M.Slate] = Color3.fromRGB(90, 100, 118), [M.Rock] = Color3.fromRGB(105, 112, 125) }),
		decor = {
			{ kind = "tree", styles = { "snowpine" }, count = 280 },
			{ kind = "rock", styles = { "ice", "stone" }, count = 110 },
			{ kind = "bush", styles = { "snowdrift" }, count = 120 },
		},
		pois = ALL_POIS,
		poiCount = 9,
		outerChests = 28,
		style = {
			stone = M.Slate,
			stoneColors = {
				Color3.fromRGB(120, 130, 150),
				Color3.fromRGB(100, 110, 128),
				Color3.fromRGB(140, 150, 165),
			},
			floor = M.Slate,
			floorColor = Color3.fromRGB(110, 120, 140),
			shrine = M.Marble,
			shrineColor = Color3.fromRGB(215, 230, 245),
			wood = Color3.fromRGB(90, 70, 55),
			accent = Color3.fromRGB(110, 220, 255),
			plaza = M.Slate,
			plazaColor = Color3.fromRGB(100, 112, 130),
			dais = M.Marble,
			daisColor = Color3.fromRGB(220, 232, 245),
		},
		lighting = { ClockTime = 9.5, Brightness = 2.2, OutdoorAmbient = Color3.fromRGB(130, 145, 170) },
		atmosphere = {
			Density = 0.38,
			Offset = 0.1,
			Color = Color3.fromRGB(215, 230, 250),
			Decay = Color3.fromRGB(140, 160, 200),
			Glare = 0.1,
			Haze = 2.2,
		},
		water = { color = Color3.fromRGB(80, 140, 180), transparency = 0.5 },
		weather = "Snow",
	},
	{
		id = "Ashen",
		name = "Ashen Wastes",
		icon = "🌋",
		description = "A volcanic wasteland. Black rock, dead trees, and lava lakes that burn.",
		radius = 400,
		terrain = {
			base = 14,
			hills = 30,
			hillScale = 140,
			detail = 18,
			rough = 6,
			mountains = 95,
			liquidLevel = 6,
			liquid = M.CrackedLava,
			peakHeight = 999,
			cliffHeight = 46,
		},
		materials = {
			surface = M.Basalt,
			alt = M.Slate,
			alt2 = M.Ground,
			shore = M.Basalt,
			cliff = M.Rock,
			peak = M.Basalt,
			under = M.Basalt,
		},
		colors = colors({
			[M.Ground] = Color3.fromRGB(70, 64, 62),
			[M.Slate] = Color3.fromRGB(60, 56, 58),
			[M.Rock] = Color3.fromRGB(78, 72, 72),
		}),
		decor = {
			{ kind = "tree", styles = { "dead" }, count = 150 },
			{ kind = "rock", styles = { "obsidian", "stone" }, count = 110 },
			{ kind = "bush", styles = { "ashpile" }, count = 70 },
		},
		pois = ALL_POIS,
		poiCount = 9,
		outerChests = 26,
		style = {
			stone = M.Basalt,
			stoneColors = { Color3.fromRGB(55, 50, 52), Color3.fromRGB(70, 62, 60), Color3.fromRGB(45, 42, 46) },
			floor = M.Basalt,
			floorColor = Color3.fromRGB(50, 46, 48),
			shrine = M.Basalt,
			shrineColor = Color3.fromRGB(60, 52, 54),
			wood = Color3.fromRGB(55, 40, 32),
			accent = Color3.fromRGB(255, 120, 40),
			plaza = M.Basalt,
			plazaColor = Color3.fromRGB(48, 44, 46),
			dais = M.Slate,
			daisColor = Color3.fromRGB(80, 70, 70),
		},
		lighting = { ClockTime = 18.3, Brightness = 1.8, OutdoorAmbient = Color3.fromRGB(150, 100, 80) },
		atmosphere = {
			Density = 0.45,
			Offset = 0.2,
			Color = Color3.fromRGB(200, 130, 100),
			Decay = Color3.fromRGB(120, 50, 40),
			Glare = 0.4,
			Haze = 2.5,
		},
		water = { color = Color3.fromRGB(60, 60, 60), transparency = 0.6 },
		weather = "Ash",
		hazard = "Lava",
	},
	{
		id = "Sandsea",
		name = "Sandsea Ruins",
		icon = "🏜️",
		description = "Endless dunes, sandstone ruins and rare oases. The biggest map.",
		radius = 480,
		terrain = {
			base = 12,
			hills = 28,
			hillScale = 120,
			detail = 10,
			rough = 1.5,
			mountains = 70,
			liquidLevel = 2,
			liquid = M.Water,
			peakHeight = 999,
			cliffHeight = 50,
		},
		materials = {
			surface = M.Sand,
			alt = M.Sand,
			alt2 = M.Sandstone,
			shore = M.Sand,
			cliff = M.Sandstone,
			peak = M.Sandstone,
			under = M.Sandstone,
		},
		colors = colors({ [M.Sand] = Color3.fromRGB(218, 190, 130) }),
		decor = {
			{ kind = "tree", styles = { "cactus", "cactus", "palm" }, count = 170 },
			{ kind = "rock", styles = { "sandstone" }, count = 120 },
			{ kind = "bush", styles = { "shrub" }, count = 90 },
		},
		pois = ALL_POIS,
		poiCount = 11,
		outerChests = 30,
		style = {
			stone = M.Sandstone,
			stoneColors = {
				Color3.fromRGB(205, 170, 120),
				Color3.fromRGB(190, 150, 105),
				Color3.fromRGB(215, 185, 140),
			},
			floor = M.Sandstone,
			floorColor = Color3.fromRGB(200, 165, 115),
			shrine = M.Sandstone,
			shrineColor = Color3.fromRGB(225, 195, 150),
			wood = Color3.fromRGB(120, 90, 55),
			accent = Color3.fromRGB(255, 200, 80),
			plaza = M.Sandstone,
			plazaColor = Color3.fromRGB(190, 155, 110),
			dais = M.Marble,
			daisColor = Color3.fromRGB(235, 220, 190),
		},
		lighting = { ClockTime = 13, Brightness = 3, OutdoorAmbient = Color3.fromRGB(160, 140, 120) },
		atmosphere = {
			Density = 0.32,
			Offset = 0.1,
			Color = Color3.fromRGB(240, 215, 170),
			Decay = Color3.fromRGB(200, 150, 100),
			Glare = 0.6,
			Haze = 2,
		},
		water = { color = Color3.fromRGB(50, 150, 160), transparency = 0.5 },
		weather = "Dust",
	},
	{
		id = "Fungal",
		name = "Fungal Hollow",
		icon = "🍄",
		description = "A glowing night forest of giant mushrooms. Small, dark and deadly.",
		radius = 380,
		terrain = {
			base = 12,
			hills = 30,
			hillScale = 140,
			detail = 12,
			rough = 3,
			mountains = 90,
			liquidLevel = 5,
			liquid = M.Water,
			peakHeight = 999,
			cliffHeight = 50,
		},
		materials = {
			surface = M.LeafyGrass,
			alt = M.Grass,
			alt2 = M.Mud,
			shore = M.Mud,
			cliff = M.Rock,
			peak = M.Rock,
			under = M.Mud,
		},
		colors = colors({
			[M.LeafyGrass] = Color3.fromRGB(70, 110, 105),
			[M.Grass] = Color3.fromRGB(95, 85, 130),
			[M.Mud] = Color3.fromRGB(50, 42, 55),
			[M.Rock] = Color3.fromRGB(70, 66, 80),
		}),
		decor = {
			{ kind = "tree", styles = { "bigmushroom" }, count = 130 },
			{ kind = "rock", styles = { "mossy" }, count = 80 },
			{ kind = "bush", styles = { "smallmushroom" }, count = 220 },
		},
		pois = ALL_POIS,
		poiCount = 8,
		outerChests = 24,
		style = {
			stone = M.Slate,
			stoneColors = { Color3.fromRGB(80, 95, 90), Color3.fromRGB(70, 80, 85), Color3.fromRGB(95, 105, 100) },
			floor = M.Slate,
			floorColor = Color3.fromRGB(75, 85, 85),
			shrine = M.Marble,
			shrineColor = Color3.fromRGB(190, 175, 220),
			wood = Color3.fromRGB(80, 60, 70),
			accent = Color3.fromRGB(90, 255, 220),
			plaza = M.Slate,
			plazaColor = Color3.fromRGB(70, 75, 90),
			dais = M.Marble,
			daisColor = Color3.fromRGB(180, 170, 210),
		},
		lighting = { ClockTime = 0.5, Brightness = 1.2, OutdoorAmbient = Color3.fromRGB(110, 95, 150) },
		atmosphere = {
			Density = 0.42,
			Offset = 0.25,
			Color = Color3.fromRGB(150, 120, 200),
			Decay = Color3.fromRGB(60, 40, 110),
			Glare = 0,
			Haze = 2.4,
		},
		water = { color = Color3.fromRGB(70, 60, 120), transparency = 0.5 },
		weather = "Spores",
	},
} :: { MapDef }

MapDefs.ById = {} :: { [string]: MapDef }
for _, def in MapDefs.List do
	MapDefs.ById[def.id] = def
end

-- The plaza (and pedestal ring) are flattened to this height.
function MapDefs.plazaHeight(def: MapDef): number
	return def.terrain.base + 1
end

-- What the vote screen needs to know (plain data so it can go over a remote).
function MapDefs.summary(def: MapDef): { [string]: any }
	return {
		id = def.id,
		name = def.name,
		icon = def.icon,
		description = def.description,
		radius = def.radius,
	}
end

return MapDefs
